server:
  port: 8080

spring:
  application:
    name: coffeemachine
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

build:
  version: "1.1"

eureka:
  instance:
    prefer-ip-address: true
  #    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/  # URL du serveur Eureka
    fetch-registry: true
    register-with-eureka: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  #  security:
  #    enabled: false
  endpoint:
    shutdown:
      access: unrestricted
    health:
#      permet a docker de savoir son etat de santé
      probes:
        enabled: true
      show-details: always



info:
  app:
    name: ${spring.application.name}
    description: "Application CoffeeMachine"
    version: ${build.version}
  custom:
    myCustomInfo: "Voici une information personnalisée"

greeting:
  name: Dakota
  coffee: ${greeting.name} is drinking Coffee Cereza

account:
  message: "Welcome to Coffee App Prod"
  details:
    name: "Bob prod"
    email: "{cipher}6a3242527de0003276b89ed41bdfda41fde7348023826cdb468f7d3147ce32a2"
  phone:
    - 0202020202
    - 0351351683
