spring:
  application:
    name: coffeemachine
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
server:
  port: 8080

greeting:
  name: Dakota
  coffee: ${greeting.name} is drinking Coffee Cereza

build:
  version: "3.0"

account:
  message: "Welcome to Coffee App"
  details:
    name: "Bob"
    email: "sdbcks@bksdbc.fr"
  phone: 
  - 0202020202
  - 0351351683

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/  # URL du serveur Eureka
