spring:
  application:
    name: drinkcoffeefeignclient
server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/  # URL du serveur Eureka
    fetch-registry: true
    register-with-eureka: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  #  security:
  #    enabled: false
  endpoint:
    shutdown:
      access: unrestricted
    health:
      show-details: always

info:
  app:
    name: ${spring.application.name}
    description: "Feign client CoffeeMachine"
    version: 2.0
  custom:
    myCustomInfo: "Voici une information personnalisée"






