server:
  port: 8070

spring:
  application:
    name: eurekacoffee
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  #  security:
  #    enabled: false
  endpoint:
    shutdown:
      access: unrestricted
    health:
      #      permet a docker de savoir son etat de santé
      probes:
        enabled: true
      show-details: always